[package]
name = "wgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.10"
env_logger = "0.11.8"
log = "0.4"
wgpu = "25.0"
pollster = "0.4"
bytemuck = "1.23"
notify = "8.0.0" 
glam = "0.30.3"
image = "0.25.6"
anyhow = "1.0.98"
